name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: mvn test -Dtest="*ServiceTest,*ValidationServiceTest" -DfailIfNoTests=false
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

      - name: Generate Test Report
        if: always()
        run: mvn surefire-report:report